# Kustomization for Kurrier
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kurrier

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - pvc.yaml
  - redis.yaml
  - typesense.yaml
  - supabase.yaml
  - kurrier-app.yaml
  - ingress.yaml
# db-init.yaml 手动执行一次即可
